language: node_js
node_js: stable
addons:
  apt:
      sources:
        - google-chrome
      packages:
        - google-chrome-stable
sudo: required
before_script:
- npm install -g bower polymer-cli eslint eslint-plugin-html web-component-tester
- bower install
- polymer lint
- eslint *.html
script:
- wct
